{% set name = "cuda-nvrtc" %}
{% set version = "12.8.93" %}
{% set cuda_version = "12.8" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvrtc/{{ platform }}/cuda_nvrtc-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 992f5e4d95cb499f41e442245efa877dbd60c711451afe680a26700d61eb3843  # [linux64]
  sha256: a24bb837c214a1620924b9721dcc0ce82623626f8cead704aed4eb08038ac5d3  # [aarch64]
  sha256: a63302a077f0248a743a1a7caa7dbd80d0fac56c6cfa9c41fa05fac9b7e5eda5  # [win]

build:
  number: 1
  binary_relocation: false
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]
    - patchelf <0.18.0                      # [linux]

outputs:
  - name: cuda-nvrtc
    files:
      - lib/libnvrtc*.so.*                            # [linux]
      - targets/{{ target_name }}/lib/libnvrtc*.so.*  # [linux]
      - Library\bin\nvrtc*.dll                        # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
    test:
      requires:
        - patchelf  # [linux]
      files:
        - test-rpath.sh
      commands:
        - test -L $PREFIX/lib/libnvrtc.so.{{ version.split(".")[0] }}                            # [linux]
        - test -L $PREFIX/lib/libnvrtc.so.{{ version }}                                          # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libnvrtc.so.{{ version.split(".")[0] }}  # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/libnvrtc.so.{{ version }}                # [linux]
        - bash test-rpath.sh                                                                     # [linux]
        - if not exist %LIBRARY_BIN%\nvrtc64_*.dll exit 1                                        # [win]
        - if not exist %LIBRARY_BIN%\nvrtc-builtins64_*.dll exit 1                               # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: NVRTC native runtime libraries
      description: |
        NVRTC native runtime libraries
      doc_url: https://docs.nvidia.com/cuda/nvrtc/

  - name: cuda-nvrtc-dev
    build:
      run_exports:
        - {{ pin_subpackage("cuda-nvrtc", max_pin="x") }}
    files:
      - lib/libnvrtc*.so                            # [linux]
      - lib/pkgconfig                               # [linux]
      - targets/{{ target_name }}/include           # [linux]
      - targets/{{ target_name }}/lib/libnvrtc*.so  # [linux]
      - targets/{{ target_name }}/lib/stubs         # [linux]
      - Library\include                             # [win]
      - Library\lib\nvrtc.lib                       # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_subpackage("cuda-nvrtc", exact=True) }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - cuda-nvrtc-static >={{ version }}     # [linux]
    test:
      commands:
        - test -L $PREFIX/lib/libnvrtc.so                                     # [linux]
        - test -L $PREFIX/lib/libnvrtc-builtins.so                            # [linux]
        - test -f $PREFIX/lib/pkgconfig/nvrtc*.pc                             # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/nvrtc.h           # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libnvrtc.so           # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libnvrtc-builtins.so  # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/stubs/libnvrtc.so     # [linux]
        - if not exist %LIBRARY_INC%\nvrtc.h exit 1                           # [win]
        - if not exist %LIBRARY_LIB%\nvrtc.lib exit 1                         # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: NVRTC native runtime libraries
      description: |
        NVRTC native runtime libraries
      doc_url: https://docs.nvidia.com/cuda/nvrtc/

  - name: cuda-nvrtc-static
    files:
      - targets/{{ target_name }}/lib/*.a  # [linux]
      - Library\lib\*_static.lib           # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -f $PREFIX/targets/{{ target_name }}/lib/libnvrtc_static.a           # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/libnvrtc-builtins_static.a  # [linux]
        - if not exist %LIBRARY_LIB%\nvrtc_static.lib exit 1                        # [win]
        - if not exist %LIBRARY_LIB%\nvrtc-builtins_static.lib exit 1               # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: NVRTC native runtime libraries
      description: |
        NVRTC native runtime libraries
      doc_url: https://docs.nvidia.com/cuda/nvrtc/

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: NVRTC native runtime libraries
  description: |
    NVRTC native runtime libraries
  doc_url: https://docs.nvidia.com/cuda/nvrtc/

extra:
  recipe-maintainers:
    - conda-forge/cuda
